ninech/nctl

auth/cluster.go
auth/cluster_test.go
auth/config.go
auth/login.go
auth/login_test.go

When just logging into nctl with auth login, we don't want to change the CurrentContext of the existing kubeconfig as this is probably more confusing to the user than anything. When logging into a cluster, we keep the current behaviour and switch the CurrentContext.

login: Do not switch the CurrentContext on auth login

---

api/client.go
apply/apply.go
apply/file.go
apply/file_test.go
create/apiserviceaccount.go
create/apiserviceaccount_test.go
create/create.go
create/create_test.go
create/file.go
create/vcluster.go
create/vcluster_test.go
delete/delete.go
delete/file.go
go.mod
go.sum
main.go

This adds a few new commands to enable CRUD of any resource on the API from a yaml or json file.
```bash
$ nctl create -f asa.yaml
$ nctl apply -f asa.yaml
$ nctl delete -f asa.yaml
```

Add generic crud of resources

---

README.md
create/application.go
create/application_test.go
create/create.go
go.mod
go.sum
main.go

This adds the full app creation flow. By default it will wait until the application is fully built and released.
The args allow to configure all the settings that are currently available on the API.
The second commit retries the watch on failure. I noticed this during testing with the new API, whenever our staging env kills the watch (for whatever reason) it would fail silently and the wait would just timeout.
Note to the reviewer: Please install this branch locally and try it out against staging `nctl --api-cluster staging.nineapis.ch create app ...`.

Add application create

---

api/login.go
auth/login.go
auth/login_test.go

This allows logging into the API using a static token instead of using the OIDC login flow. This was already possible before but not really user-friendly as they would have to construct their own kubeconfig. This automates that and configures the statc token in the kubeconfig if desired.

Allow logging into API with a static token

---

get/releases.go
get/releases_test.go

This fixes the ordering logic for the ReleaseList. What we had so far only worked for outputs: `full` and `noHeader`. This commit provides a new unified approach for all output cases (including yaml pretty print).

Fix get release sorting

---

logs/application.go
logs/build.go
logs/logs.go
logs/logs_test.go

With the phase label we can now differentiate between app logs and build logs that belong to an application. So we can now view all build logs of a specific application instead of having to know the build name.
I also changed the way we build the loki query a bit so we can add arbitrary labels if required.

Add phase label to logs

---

create/application.go
delete/application.go

We should wait slightly longer for slow to build apps on create. Also the deletion wait was really short and sometimes it just takes a few more seconds than the previous 10.

fix: increase wait timeouts for app operations

---

go.mod
go.sum

This is now again using the main branch of the apis as the apps apis have been pushed.

Upgrade ninech/apis dependency

---

api/util/apps.go
auth/config.go
auth/config_test.go
auth/login.go
create/application.go
create/application_test.go
delete/application.go
delete/application_test.go
internal/test/client.go
main.go
update/application.go
update/application_test.go

This will delete git auth secrets which were created by `nctl` on application delete. If the secret is still referenced by another application, a corresponding message will be printed.

delete secrets created by nctl when deleting applications

---

auth/cluster.go
auth/login.go
main.go

This will resolve the absolute path of the nctl binary so it can be used as credential helper in the kubeconfig. It allows for locally build "nctl" versions and calling them via "./nctl" for example.

find absolute path to nctl binary

---

go.mod
go.sum

This removes the replace/exclude directives in the go.mod as it turns out these are not needed anymore after all.

fix: make go install work again

---

api/util/authentication.go
auth/config.go
auth/login.go
create/application.go
create/application_test.go
create/project_config.go
create/project_config_test.go
get/application.go
get/application_test.go
get/get.go
get/project_config_test.go
go.mod
go.sum
internal/format/command.go
internal/format/print.go
main.go
update/application.go
update/application_test.go
update/project_config.go
update/project_config_test.go

This adds basic auth functionality for applications. Basic auth can now be handled in the applications `create`, `get` and `update` commands. Furthermore the corresponding project config commands also got support. Credentials of one application or all applications can then be shown by using the `--credentials` option to the `get application` command.

Basic auth

---

create/application.go
create/application_test.go
go.mod
go.sum
update/application.go
update/application_test.go

We should support buildpack env variables. This PR adds new flags to support passing these build-time env vars on app creation/update.

Add build-time env vars to application

---

get/application.go
get/application_test.go

Gathering credentials can now be done via:
```bash
nctl get app <name> --basic-auth-credentials
```
which is more consistent with the `--basic-auth` argument on the application create command.

rename credentials argument for consistency

---

create/application.go
create/application_test.go
go.mod
go.sum
internal/format/interpolation.go
internal/format/interpolation_test.go
main.go
main_test.go

If we set defaults in the application on creation, existing content in the .deploio.yaml file will be ignored (as the config which is set on the Application itself has higher precedence). As we will always fall back to valid defaults, we can just leave them out in the application if the user did not set an explicit value.

do not set defaults in the application on creation

---

create/application.go
internal/format/command.go
main.go

Do not error on missing command/argument. Print Usage + friendly message instead (and exit). For example:
missing command:
```bash
> nctl
Usage: nctl <command> 
...
Your query: "nctl": expected one of "get",  "auth",  "completions",  "create",  "apply",  ...
```
```bash
> nctl get
Usage: nctl get <command>
...
Your query: "nctl get": expected one of "clusters",  "apiserviceaccounts",  "projects",  "applications",  "builds",  ...
```
missing arg:
```bash
> nctl delete project
Usage: nctl delete project (proj) <name>
...
Your query: "nctl delete project": expected "<name>"
```

Do not error on missing command/argument

---

get/releases.go

As the same short option already exists for getting builds, we should have them for releases as well.

add a short option to refer to the application when listing releases

---

.goreleaser.yaml

From the go releaser docs:
#
#
name: package-bin

add -bin suffix for AUR package

---

auth/cluster.go
auth/login.go
auth/login_test.go
auth/set_org.go

Display `whoami` information on successful login. It displays user name for an OIDC login, and Service Account name for a static API token login.

Add whoami information on successful login

---

api/util/apps.go
update/application.go
update/application_test.go

In case a build fails, there's no idiomatic way to retry it. Sometimes the failure is temporary, such as an image upload that fails and a simple retry would fix it. There's a workaround that works well but is maybe not the most user-friendly: 
```bash
`nctl update app <app> --build-env=BUILD_TRIGGER=$(date)`
```
A very pragmatic solution is to simply hide this behind a retry-build flag. And this PR does just that.

Add app build retries

---

auth/config.go
auth/set_org.go
auth/whoami.go
auth/whoami_test.go
main.go

This PR fixes the `nctl auth set-org` command so that it no longer overrides the login method currently defined in .kube/config (static API token or OIDC) with OIDC.
It also adds a small feature to display a list of available organizations when an organization name is not specified (only for OIDC login method).

Fix set-org command

---

update/application.go
update/application_test.go

the update command just updates the secret if it already exists, meaning it fails if you want to enable git auth after creating the app. This will call create if the secret could not be found.

fix: allow enabling git auth using update command

---

update/application.go
update/application_test.go

The env removal only worked when both parameters were specified. Since we also did it like this in the test, it still passed.

fix: panic during env removal

---

api/util/apps.go
create/project_config.go
create/project_config_test.go
get/project_config.go
update/application.go
update/project_config.go
update/project_config_test.go

This makes it possible to configure deploy-jobs with configs.
mono-infra#845

feat: add deploy-job to config create/update

---

create/application.go
get/application.go
get/application_test.go

The value of the CNAME Target column is technically used for a potential CNAME DNS record, but also for an ALIAS record or an IP address resolution which is needed when creating an A record. That is why we rename it to `DNS TARGET`.

rename output column

---

.github/workflows/go.yml
create/application.go
go.mod
go.sum

Related to: 
https://gitlab.nine.ch/ninech/platform/mono-infra/-/issues/896
https://gitlab.nine.ch/ninech/platform/mono-infra/-/issues/897
In addition, this PR upgrades nctl to go 1.21

delete git auth secret when app creation fails & do not create git auth secret if it already exists

---

api/util/apps.go
api/validation/apps.go
api/validation/git_information_client.go
api/validation/git_information_client_test.go
create/application.go
create/application_test.go
internal/test/apps.go
internal/test/git_information_service.go
update/application.go
update/application_test.go

This implements the usage of the git information service into `nctl`. It allows to check if the specified git repository and revision can be accessed/found.

use git information service on app creation and updates

---

update/application.go
update/application_test.go
update/project_config.go
update/project_config_test.go

using pointers breaks kong's arg parsing somewhat as it fails to merge multiple values of the same arg. Removing the pointer fixes that while still making it possible to detect if the arg has been supplied or not as a map has nil as the zero value.

fix: do not use pointers for env maps

---

logs/build.go

Retrieving all possible builds of a project is not really useful as it does not indicate the application name of the corresponding build. Because of this, we require either a build name or an application name when retrieving build logs.

require build name or application name on build logs

---

create/mysql.go
create/mysql_test.go
go.mod
go.sum

fix(mysql): avoid missing param error and raise cli timeout for --wait

---

create/application.go

the message was misaligned as it lacked a space between the spinner and the message. Since the format.ProgrssMessagef function handles the formatting for spinners, we simply call that. While at it, we also use the proper subscript character for the 2.
```bash
Creating new application
✓ testing repository access 🔐
✓ created application "profound-barracuda" 🏗
✓ waiting for build to start ⏳
✓ building application 📦
✓ releasing application 🚦
✓ release available ⛺
✓co2 compensating the app 🌳
Creating new application
✓ testing repository access 🔐
✓ created application "intent-chat" 🏗
✓ waiting for build to start ⏳
✓ building application 📦  
✓ releasing application 🚦
✓ release available ⛺
✓ CO₂ compensating the app 🌳
```

fix: app co2 compensation message format

---

create/cloudvm.go
go.mod
go.sum
update/cloudvm.go

This adds a few flags to configure booting a CloudVM into rescue.
The second commit just adjusts some of the CloudVM flags and help texts.

feat: add rescue boot flags

---

auth/auth.go
auth/print_access_token.go

This is a convenience function to print the API client access token to stdout. Mainly useful when testing things on the API with curl and maybe some scriping use-cases.

feat: add auth print-access-token command

---

create/create.go
create/keyvaluestore.go
create/keyvaluestore_test.go
create/mysql.go
create/mysql_test.go
create/postgres.go
create/postgres_test.go
delete/delete.go
delete/postgres.go
delete/postgres_test.go
get/get.go
get/postgres.go
get/postgres_test.go
go.mod
go.sum
internal/test/postgres.go
main.go
update/keyvaluestore.go
update/keyvaluestore_test.go
update/mysql.go
update/mysql_test.go
update/postgres.go
update/postgres_test.go
update/update.go

Implements ninech/managed-services/backlog#581

feat(postgres): Add resource

---

api/client.go
auth/print_access_token.go
auth/set_project.go
auth/whoami.go
auth/whoami_test.go
create/application.go
delete/delete.go
get/build.go
get/clusters.go
get/get.go
internal/test/client.go
logs/logs.go
main.go
predictor/predictor.go
update/application.go
update/update.go

This adds initial support for dynamic completion. For example `nctl update application <tab><tab>` will return a list of applications in the current project. There are some edge-cases where the arg/flag name does not match the resource name. To make these cases work, they can be added to a map in the predictor.

feat: add dynamic completion

---

.goreleaser.yaml

This causes goreleaser to create a draft release so we can manually edit the release notes before we publish it.

release: do not auto-publish releases

---

api/util/apps.go

When updating an app with an unrelated change, we should not sort the existing env vars as that can trigger an unexpected build. We simply return the old env vars if the new envs and to delete is empty.

fix: do not update/sort env vars when nothing changes

---

api/util/release.go
exec/application.go
exec/application_test.go
exec/exec.go
get/releases.go
get/releases_test.go
go.mod
go.sum
main.go

This implements the execution of commands in deplo.io application replicas. If there are multiple replicas, the first replica will be used. If no command is given, a shell will be tried to start. For Dockerfile built applications this will only succeed if `/bin/sh` is a valid shell.

implement replica exec

---

get/all.go
get/all_test.go

This allows to only show certain resource types when listing all existing resources. It helps in finding resources without the need for a specific nctl implementation.

allow to list only certain resource types

---

api/log/client.go

Most of the time when the client closes the connection (nctl is terminated by ctrl+c) we get an ErrCloseSent so we should ignore it and not output an error to the user.

fix: ignore ErrCloseSent during log tail

---

create/application.go
create/create.go
delete/delete.go
internal/logbox/logbox.go
main.go

This fixes a number of issues with the cancel/error handling while the
logbox (tea program) is running. Previously input was sent to the tea
program, which meant we had to handle ctrl+c/ctrl+d explicitly. Now the
tea program is stopped using the context and also in afterWait since
it's important to call `p.Wait()` so that the console is restored
properly before nctl exits.

fix: improve logbox interrupt handling

---

api/client.go
auth/print_access_token.go
auth/whoami.go
create/application.go
get/build.go
main.go
update/application.go

In a previous PR, we changed the client to initialize the token once during creation of the client. This is problematic for longer-running processes such as creating an app where the token might expire at runtime. The only reason for putting the token into the client config was an issue with the autocompletion where the dynamic exec config fails for some shells.

fix: use dynamic auth by default

---

get/all.go
get/all_test.go

With the introduction of the `ClusterData` non-namespaced resource (to allow for connecting to deplo.io app replicas), the `nctl get all` command printed `ClusterData` content which is not really relevant for users. Furthermore some warnings have been shown for resources where list permissions are lacking. These warnings get suppressed by default now.

fix get all command

---

.github/workflows/go.yml
.github/workflows/release.yml
api/log/client.go
create/application.go
update/application.go

if you do not set the language explicitly, it will always be nil currenlty

fix the update command with the language

---

auth/whoami.go

A small thing I noticed while playing around with `nctl`.

Fix a typo in whoami.go

---

create/mysql.go
create/mysql_test.go
create/postgres.go
create/postgres_test.go

Use machine types from API package.

refactor: default machine types

---

main.go

ninech/platform/mono-infra#1120

Add error handling for command-line arguments to prevent browser error pop-ups

---

main.go

Instead of trying to call parse to default to the kong value, we now put the defualt API cluster into a const and use it in the default and when constructing the completion client. Additionally we check if the env var has been set to override the cluster.

fix: use default API cluster in autocomplete predictor

---

README.md

#104 Add `sudo` to `apt-get` commands in `README.md`

fix: debian/ubuntu install instructions 2

---

.goreleaser.yaml
go.mod
go.sum
main.go

This MR replaces [github.com/willabides/kongplete](https://github.com/willabides/kongplete) with [github.com/jotaen/kong-completion](https://github.com/jotaen/kong-completion). 
Both libraries are fairly similar, as kong-completion's [README](https://github.com/jotaen/kong-completion/blob/main/README.md) even states:
> This library was originally based on [kongplete](https://github.com/WillAbides/kongplete).
The main difference is that the new library allows to pass the shell for shell completions. Which allows to install completions when installing a package.

Improve Completion

---

.goreleaser.yaml
completions/nctl.bash
completions/nctl.fish
completions/nctl.zsh

Using `post_install` doesn't properly register the completion files. And its also very neat to run `nctl` while installing.

fix: brew completion

---

predictor/predictor.go

This changes the completion mechanism to only gather a valid OIDC token if completion was requested rather then on every invocation of nctl. This fixes https://github.com/ninech/nctl/issues/159.

only get token if tab completion was executed

---

.goreleaser.yaml

This MR adds configuration to `goreleaser` so a docker image will be built and pushed to the Github container registry.
It utilizes `ko`, so no Docker runtime is necessary: https://goreleaser.com/customization/ko/

build: add docker image build

---

api/client.go
api/log/client.go
create/application.go
main.go

This PR provides improvements about displaying the build and release logs.

improve log and version displaying

---

.github/workflows/release.yml
go.sum

As we push a `nctl` container image when releasing, we need to login to the github container registry before doing this.

Add docker login

---

.github/workflows/release.yml

We forgot to add the permission of packages pushing to the pipeline token.

allow the pipeline token to push docker images

---

delete/vcluster.go

Instead of erroring out when the removal of the vcluster from the kubeconfig fails, we instead just print a warning. The vcluster might have been created outside of nctl and might not be present in the local kubeconfig.

fix: print warning when deletion of kubeconfig fails

---

internal/format/print.go

Before disk sizes in clusters have been wrongly marshaled. By providing a custom marshaler for the `*resource.Quantity` type we fix this.

fix displaying of resource.Quantity sizes

---

api/client.go
api/util/apps.go
exec/application.go
get/application.go
get/get.go
go.mod
go.sum

This adds a new `stats` output format for the `get app` command. It prints status information about the app replicas and also some very basic metrics. The `get app` help has been extended to explain all the columns of the stats output.
Here's what the output looks like:
```
$ nctl get apps -o stats
PROJECT        NAME    REPLICA                  STATUS   CPU   CPU%   MEMORY   MEMORY%   RESTARTS   LASTEXITCODE
nine-staging   rails   rails-9f6bdb676-crlrf    ready    1m    0.8%   121MiB   47.4%     0          <none>
nine-staging   rails   rails-9f6bdb676-2pfps    ready    1m    0.8%   123MiB   48.4%     0          <none>
nine-staging   rails   rails-9f6bdb676-sd9mm    ready    1m    0.8%   122MiB   48.0%     1          137 (Out of memory)
```

feat: add app stats output

---

api/log/client.go
api/log/output.go
api/util/apps.go
create/application.go
exec/application.go
get/application.go
get/releases.go
go.mod
go.sum
logs/application.go
logs/build.go
logs/logs.go
logs/logs_test.go
update/application.go

This adds worker jobs to the app create/update commands. As a limitation
of CLI flags, it only allows to define one worker job on creation. With
update, you can add/remove as many as possible.

 feat: add worker jobs

---

main.go

As these flags are only used internally during development, we hide them from the normal help output.

do not show --api-cluster and --log-api-address

---

api/util/apps.go
get/application.go

If an app has nothing but failing releases (or even just the first release fails), the stats output should still show the failing replica to simplify troubleshooting.

fix: app stats not showing replicas of failing releases

---

exec/application.go

When using a custom (non-default) PATH environment variable, we need to make sure to always being able to launch the `launcher` binary.

use an absolute path for the launcher binary

---

create/create.go
delete/delete.go
exec/exec.go
get/get.go
logs/logs.go
update/update.go

This adds the singular long version application as an alias.

fix: add application alias

---

api/client.go
api/util/authentication.go
auth/set_org.go
auth/set_project.go
auth/whoami.go
create/project.go
delete/project.go
get/get.go
predictor/predictor.go
update/project.go

When setting the project or organization, it will now warn you if the
project does not exist, your current user does not have access to it or
if the organization is not in the list of available organizations. We
don't error out to still support some use-cases where a user might not
have the permission to get a project or might not be fully part of an
org but might still have access to some resource in it.
The first commit just refactors some code I had to touch for this.

feat: warn when setting project/org

---

api/log/client.go
create/application.go

* Removes labels on the create error logs
* Makes logbox quit when outputting error logs to avoid duplicate logs on the screen
* Relevant logs should now be shown a bit more reliably by tailing for a few seconds

fix: improve create error logs

---

get/application.go

The stats command was displaying the wrong project when requesting the stats output of cross-project, it always displayed the project of the client and not the app itself.

fix: stats output app project

---

auth/login.go
auth/login_test.go
internal/format/print.go

If you execute `nctl auth login` in a non-interactive environment (e.g. CI/CD) and forget to set `--api-token`, the browser should not try to open - you should see an error message instead.

auth login in non-interactive env should not block

---

create/create.go

Extends the create message to include the project where the resource was created:
✓ created APIServiceAccount "foo" in project "bar" 🏗

feat: display project when creating resource

---

create/application.go
create/application_test.go

As the basic-auth secret is now handled separately from the basic-auth settings (enabled/disabled), it will be constantly referenced in the application status. That is why we can not use it anymore to decide if basic-auth was enabled or not.

only show credentials if basic-auth was set by user

---

api/log/output.go
logs/build.go
logs/logs.go
logs/logs_test.go
main.go

* Increases default look-back to match retention
* Add error messages when requested logs exceed retention
* Adds flags to get logs for absolute time ranges
* Add error message for when no logs have been found

Improve Logs UX

---

api/get.go
api/list.go
get/all.go
get/apiserviceaccount.go
get/application.go
get/build.go
get/cloudvm.go
get/clusters.go
get/get.go
get/keyvaluestore.go
get/mysql.go
get/postgres.go
get/project.go
get/releases.go
logs/application.go
logs/build.go

This makes our special list function available to other packages than get and uses it in logs.

refactor: move list to api package

---

update/application.go
update/application_test.go

Currently, Deploio only supports a "Retry Build" trigger. However, there are niche cases where also triggering a new release independently is useful. For example, after a successful build but failed release due to a broken DB migration, you might resolve the issue at the DB level without code changes, requiring only a manual release retry.

feat: add app release retry

---

api/util/apps.go

Deploio apps currently support two methods for Git authentication:
* `spec.forProvider.git.auth.username` and `password` for inline credentials
* `spec.forProvider.git.auth.fromSecret` to reference a Kubernetes secret
In practice, `nctl` exclusively use the `fromSecret` method. Maintaining both options adds unnecessary complexity, and it looks like the inline method is not used at the moment.

feat: remove app git auth inline fields

---

create/mysql.go
create/mysql_test.go
create/postgres.go
create/postgres_test.go
update/mysql.go
update/mysql_test.go
update/postgres.go
update/postgres_test.go

PR #217 introduced the new machine type implementation but we missed that mysql/postgres used the type directly in the command struct which does not work anymore. The machinetype needs to be constructed first using NewMachineType.

fix: machinetype create/update for DBs

---

go.mod
go.sum

This will fix a bug which disabled all networking connections for newly created KVS instances.

update ninech API definitions

---

auth/set_project.go
main.go
predictor/predictor.go

This adds a new predictor that works on a fixed kind and does not need to resolve the kind by the last argument name. The client creation function has been moved out of main since there is no reason for it to be there.

feat: improve predictor

---

copy/application.go
copy/application_test.go
copy/copy.go
main.go

This implements a simple copy app command. The whole spec is copied with
some exceptions:
* Hosts are not copied to avoid conflicts with the old app unless
explicitly forced with the `--copy-hosts` flag
* The new app is in paused state unless explicitly forced with the
`--start` flag
The new app can be copied into a different project if desired.

feat: implement copy app command

---

auth/auth.go
auth/login.go
auth/login_test.go
auth/logout.go
auth/oidc.go
internal/format/command.go
main.go

This simplifies registering commands that don't need an API client.

refactor: simplify command selection without API client

---

create/apiserviceaccount.go
create/apiserviceaccount_test.go
go.mod
go.sum
update/apiserviceaccount.go
update/apiserviceaccount_test.go
update/update.go

This adds a new flag to the APIServiceAccount to enable organization wide access. As this is the first updatable field of an ASA it also adds a new update command.

feat: add OrganizationAccess flag to ASA

---

api/util/apps.go

Since we added the CAA records to the verification status, hosts show up twice in `get apps`. We now ignore CAA records as the backend accepts hosts as verified when either TXT or CNAME is there.

fix: remove duplicate verified app hosts

---

api/util/apps.go
api/util/apps_test.go
create/application.go
create/application_test.go
get/project_config_test.go
update/application.go
update/application_test.go

We've added new flags (--sensitive-env and --sensitive-build-env) to the create and update commands. These flags allow users to mark variables as sensitive.
Masking logic were created to redact their values (*****) in the command output.
```
./nctl get configs
PROJECT    NAME    SIZE    REPLICAS    PORT    ENVIRONMENT_VARIABLES    BASIC_AUTH    DEPLOY_JOB    AGE
test             test                                                  env_test=*****           false         <none>        14m
```
Note: We didn't apply masking for YAML or JSON output. This is by design because these formats are used by automation tools etc

adding flags and new funcions for the sensitive fields
