- README.md
Doesn't work with an 'apt update' in between. 
Added a newline at the end :)
> Added apt update

- api/util/apps.go
- create/application.go
- create/create.go
- delete/application.go
- delete/application_test.go
- delete/delete.go
- delete/delete_test.go
- get/apiserviceaccount.go
- get/application.go
- get/application_test.go
- get/clusters.go
- get/get.go
This adds application get and delete commands. For get I created some helper functions to print the namespace consistently across commands (and only if queried over all namespaces).
> Application get/delete

- api/util/apps.go
- create/application.go
- create/application_test.go
- main.go
- update/application.go
- update/application_test.go
- update/update.go
This adds an update command for the app. While it is possible to update an app using apply, it's not exactly the most user-friendly and also not great for scripting.
> Add app update command

- get/build.go
So it is a bit more consistent with the release command.
> Add application row to build output

- .gitignore
- get/get.go
- get/releases.go
- get/releases_test.go
This adds `get releases` command (view your app’s release history).
> Add release history

- api/util/apps.go
- create/create.go
- create/project_config.go
- create/project_config_test.go
- delete/application.go
- delete/delete.go
- delete/project_config.go
- delete/project_config_test.go
- get/get.go
- get/project_config.go
- get/project_config_test.go
- get/releases_test.go
- internal/test/naming.go
- internal/test/time.go
- update/project_config.go
- update/project_config_test.go
- update/update.go
This adds `create/delete/get/update config` commands to enable CRUD of ProjectConfiguration resource.
> Add config create/delete/get/update commands

- create/create.go
Whenever a watch error happens, we used to show a line like "watch failed". This can be very confusing to the user as we anyways retry when that happens and it has nothing to do with the actual creation process of the resource. This hides the error completely and unless we are not running into the backoff it will just continue. The backoff also has been increased to account for the API cancelling watches sometimes.
> fix: Improve wait error handling

- get/build.go
Without a tag, using the pulled image with docker/podman is a bit cumbersome as you have to first find out the image ID. With a tag it's possible to just do `docker run <image name>`.
> Tag pulled build images with latest

- create/application.go
- create/application_test.go
This allows to read the SSH private key from a local file instead of direct from the CLI/env variable. It furthermore validates the PEM encoding of the given content.
> allow to read SSH private key from file

- create/application.go
- create/application_test.go
- go.mod
- go.sum
- update/application.go
- update/application_test.go
this adds all deploy-job related flags to create/update of the app.
> Add deploy job to app

- api/util/apps.go
- create/application.go
Related to https://gitlab.nine.ch/gcp/mono-infra/-/issues/769
> error out when credentials are empty

- .goreleaser.yaml
Closes https://gitlab.nine.ch/gcp/mono-infra/-/issues/752
> add AUR as a goreleaser target

- .goreleaser.yaml
Created a new repo https://aur.archlinux.org/packages/nctl-bin
> change to new aur repo

- README.md
Closes https://gitlab.nine.ch/gcp/mono-infra/-/issues/752
> document how to install nctl on arch

- .goreleaser.yaml
Install the licence and README.md
> fix the custom package instructions

- logs/build.go
- logs/logs.go
Closes https://gitlab.nine.ch/gcp/mono-infra/-/issues/812
> Logs for build since creation and for app since one hour

- api/login.go
- auth/auth.go
- auth/logout.go
- go.mod
- go.sum
- internal/format/command.go
- main.go
Closes https://gitlab.nine.ch/gcp/mono-infra/-/issues/674
> add the auth logout command

- create/application.go
ninech/platform/mono-infra#843
> add co2 compensation msg with spinner

- api/util/apps.go
- update/application.go
See individual commits. This fixes internal issue #1012.
> Improve git validation on app update

- create/cloudvm.go
- create/cloudvm_test.go
- create/create.go
- delete/cloudvm.go
- delete/cloudvm_test.go
- delete/delete.go
- get/cloudvm.go
- get/cloudvm_test.go
- get/get.go
- go.mod
- go.sum
- internal/test/cloudvm.go
- update/cloudvm.go
- update/cloudvm_test.go
- update/update.go
https://gitlab.nine.ch/ninech/platform/mono-infra/-/issues/1039
> add cloudvms to nctl

- README.md
> fix: debian/ubuntu install instructions

- main.go
This fixes the `nctl --version` command which was showing `dev` for released versions before.
> fix displaying of nctl version

- api/util/apps.go
- get/all.go
- get/all_test.go
- get/apiserviceaccount.go
- get/application.go
- get/application_test.go
- get/build.go
- get/cloudvm.go
- get/cloudvm_test.go
- get/clusters.go
- get/get.go
- get/keyvaluestore.go
- get/mysql.go
- get/postgres.go
- get/project.go
- get/project_config.go
- get/project_test.go
- get/releases.go
ninech/platform/mono-infra#1147
> adjust nctl output when searching for apps

- get/get.go
Adds some new aliases to the cluster get command.
> feat: add cluster/vcluster aliases

- get/application.go
This improves statistics displaying for app replicas, worker job replicas and scheduled job replicas by considering the individual max sizes
> fix stats displaying

- update/application.go
This fixes the update logic for scheduled jobs.
> fix job updating

- create/postgres.go
Use the correct MachineType list
> refactor: use storage.PostgresMachineTypes instead of storage.MySQLMachineTypes

- .gitignore
- api/util/apps.go
- copy/application.go
- copy/application_test.go
- delete/application.go
- delete/application_test.go
Also adds a commit to delete static egress(es) on deletion of an app.
> feat: copy static egress when copying app

- get/opensearch.go
- get/opensearch_test.go
- update/opensearch.go
- update/opensearch_test.go
- add option to add snapshot bucket users
- add option to print snapshot bucket
- add tests for adding snapshot bucket users
- add tests for printing snapshot bucket
> feat(opensearch): support for snapshot bucket management

- auth/client_credentials.go
This is especially useful in CI/CD when setting the client_id/client_secret via env.
> feat: improve client_credentials login error
